/**
 */
package com.hundsun.ares.studio.jres.model.chouse.provider;

import java.util.ArrayList;
import java.util.Collection;

import org.eclipse.emf.common.notify.Adapter;
import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.Notifier;
import org.eclipse.emf.edit.provider.ChangeNotifier;
import org.eclipse.emf.edit.provider.ComposeableAdapterFactory;
import org.eclipse.emf.edit.provider.ComposedAdapterFactory;
import org.eclipse.emf.edit.provider.IChangeNotifier;
import org.eclipse.emf.edit.provider.IDisposable;
import org.eclipse.emf.edit.provider.IEditingDomainItemProvider;
import org.eclipse.emf.edit.provider.IItemLabelProvider;
import org.eclipse.emf.edit.provider.IItemPropertySource;
import org.eclipse.emf.edit.provider.INotifyChangedListener;
import org.eclipse.emf.edit.provider.IStructuredItemContentProvider;
import org.eclipse.emf.edit.provider.ITreeItemContentProvider;

import com.hundsun.ares.studio.jres.model.chouse.util.ChouseAdapterFactory;

/**
 * This is the factory that is used to provide the interfaces needed to support Viewers.
 * The adapters generated by this factory convert EMF adapter notifications into calls to {@link #fireNotifyChanged fireNotifyChanged}.
 * The adapters also support Eclipse property sheets.
 * Note that most of the adapters are shared among multiple instances.
 * <!-- begin-user-doc -->
 * <!-- end-user-doc -->
 * @generated
 */
public class ChouseItemProviderAdapterFactory extends ChouseAdapterFactory implements ComposeableAdapterFactory, IChangeNotifier, IDisposable {
	/**
	 * This keeps track of the root adapter factory that delegates to this adapter factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ComposedAdapterFactory parentAdapterFactory;

	/**
	 * This is used to implement {@link org.eclipse.emf.edit.provider.IChangeNotifier}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IChangeNotifier changeNotifier = new ChangeNotifier();

	/**
	 * This keeps track of all the supported types checked by {@link #isFactoryForType isFactoryForType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Collection<Object> supportedTypes = new ArrayList<Object>();

	/**
	 * This constructs an instance.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public ChouseItemProviderAdapterFactory() {
		supportedTypes.add(IEditingDomainItemProvider.class);
		supportedTypes.add(IStructuredItemContentProvider.class);
		supportedTypes.add(ITreeItemContentProvider.class);
		supportedTypes.add(IItemLabelProvider.class);
		supportedTypes.add(IItemPropertySource.class);
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.hundsun.ares.studio.jres.model.chouse.TableSpaceProperty} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected TableSpacePropertyItemProvider tableSpacePropertyItemProvider;

	/**
	 * This creates an adapter for a {@link com.hundsun.ares.studio.jres.model.chouse.TableSpaceProperty}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTableSpacePropertyAdapter() {
		if (tableSpacePropertyItemProvider == null) {
			tableSpacePropertyItemProvider = new TableSpacePropertyItemProvider(this);
		}

		return tableSpacePropertyItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.hundsun.ares.studio.jres.model.chouse.TableSpaceRelationProperty} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected TableSpaceRelationPropertyItemProvider tableSpaceRelationPropertyItemProvider;

	/**
	 * This creates an adapter for a {@link com.hundsun.ares.studio.jres.model.chouse.TableSpaceRelationProperty}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTableSpaceRelationPropertyAdapter() {
		if (tableSpaceRelationPropertyItemProvider == null) {
			tableSpaceRelationPropertyItemProvider = new TableSpaceRelationPropertyItemProvider(this);
		}

		return tableSpaceRelationPropertyItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.hundsun.ares.studio.jres.model.chouse.TableBaseProperty} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected TableBasePropertyItemProvider tableBasePropertyItemProvider;

	/**
	 * This creates an adapter for a {@link com.hundsun.ares.studio.jres.model.chouse.TableBaseProperty}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTableBasePropertyAdapter() {
		if (tableBasePropertyItemProvider == null) {
			tableBasePropertyItemProvider = new TableBasePropertyItemProvider(this);
		}

		return tableBasePropertyItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.hundsun.ares.studio.jres.model.chouse.HistoryProperty} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected HistoryPropertyItemProvider historyPropertyItemProvider;

	/**
	 * This creates an adapter for a {@link com.hundsun.ares.studio.jres.model.chouse.HistoryProperty}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createHistoryPropertyAdapter() {
		if (historyPropertyItemProvider == null) {
			historyPropertyItemProvider = new HistoryPropertyItemProvider(this);
		}

		return historyPropertyItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.hundsun.ares.studio.jres.model.chouse.RevisionHistoryProperty} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected RevisionHistoryPropertyItemProvider revisionHistoryPropertyItemProvider;

	/**
	 * This creates an adapter for a {@link com.hundsun.ares.studio.jres.model.chouse.RevisionHistoryProperty}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createRevisionHistoryPropertyAdapter() {
		if (revisionHistoryPropertyItemProvider == null) {
			revisionHistoryPropertyItemProvider = new RevisionHistoryPropertyItemProvider(this);
		}

		return revisionHistoryPropertyItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.hundsun.ares.studio.jres.model.chouse.Modification} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ModificationItemProvider modificationItemProvider;

	/**
	 * This creates an adapter for a {@link com.hundsun.ares.studio.jres.model.chouse.Modification}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createModificationAdapter() {
		if (modificationItemProvider == null) {
			modificationItemProvider = new ModificationItemProvider(this);
		}

		return modificationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.hundsun.ares.studio.jres.model.chouse.StockTableProperty} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected StockTablePropertyItemProvider stockTablePropertyItemProvider;

	/**
	 * This creates an adapter for a {@link com.hundsun.ares.studio.jres.model.chouse.StockTableProperty}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createStockTablePropertyAdapter() {
		if (stockTablePropertyItemProvider == null) {
			stockTablePropertyItemProvider = new StockTablePropertyItemProvider(this);
		}

		return stockTablePropertyItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.hundsun.ares.studio.jres.model.chouse.StockColumnProperty} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected StockColumnPropertyItemProvider stockColumnPropertyItemProvider;

	/**
	 * This creates an adapter for a {@link com.hundsun.ares.studio.jres.model.chouse.StockColumnProperty}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createStockColumnPropertyAdapter() {
		if (stockColumnPropertyItemProvider == null) {
			stockColumnPropertyItemProvider = new StockColumnPropertyItemProvider(this);
		}

		return stockColumnPropertyItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.hundsun.ares.studio.jres.model.chouse.StockIndexProperty} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected StockIndexPropertyItemProvider stockIndexPropertyItemProvider;

	/**
	 * This creates an adapter for a {@link com.hundsun.ares.studio.jres.model.chouse.StockIndexProperty}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createStockIndexPropertyAdapter() {
		if (stockIndexPropertyItemProvider == null) {
			stockIndexPropertyItemProvider = new StockIndexPropertyItemProvider(this);
		}

		return stockIndexPropertyItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.hundsun.ares.studio.jres.model.chouse.StockTSRelationProperty} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected StockTSRelationPropertyItemProvider stockTSRelationPropertyItemProvider;

	/**
	 * This creates an adapter for a {@link com.hundsun.ares.studio.jres.model.chouse.StockTSRelationProperty}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createStockTSRelationPropertyAdapter() {
		if (stockTSRelationPropertyItemProvider == null) {
			stockTSRelationPropertyItemProvider = new StockTSRelationPropertyItemProvider(this);
		}

		return stockTSRelationPropertyItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.hundsun.ares.studio.jres.model.chouse.StockProjectProperty} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected StockProjectPropertyItemProvider stockProjectPropertyItemProvider;

	/**
	 * This creates an adapter for a {@link com.hundsun.ares.studio.jres.model.chouse.StockProjectProperty}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createStockProjectPropertyAdapter() {
		if (stockProjectPropertyItemProvider == null) {
			stockProjectPropertyItemProvider = new StockProjectPropertyItemProvider(this);
		}

		return stockProjectPropertyItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.hundsun.ares.studio.jres.model.chouse.StockDBContextProperty} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected StockDBContextPropertyItemProvider stockDBContextPropertyItemProvider;

	/**
	 * This creates an adapter for a {@link com.hundsun.ares.studio.jres.model.chouse.StockDBContextProperty}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createStockDBContextPropertyAdapter() {
		if (stockDBContextPropertyItemProvider == null) {
			stockDBContextPropertyItemProvider = new StockDBContextPropertyItemProvider(this);
		}

		return stockDBContextPropertyItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.hundsun.ares.studio.jres.model.chouse.AddTableModification} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected AddTableModificationItemProvider addTableModificationItemProvider;

	/**
	 * This creates an adapter for a {@link com.hundsun.ares.studio.jres.model.chouse.AddTableModification}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createAddTableModificationAdapter() {
		if (addTableModificationItemProvider == null) {
			addTableModificationItemProvider = new AddTableModificationItemProvider(this);
		}

		return addTableModificationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.hundsun.ares.studio.jres.model.chouse.HisTableColumn} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected HisTableColumnItemProvider hisTableColumnItemProvider;

	/**
	 * This creates an adapter for a {@link com.hundsun.ares.studio.jres.model.chouse.HisTableColumn}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createHisTableColumnAdapter() {
		if (hisTableColumnItemProvider == null) {
			hisTableColumnItemProvider = new HisTableColumnItemProvider(this);
		}

		return hisTableColumnItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.hundsun.ares.studio.jres.model.chouse.AddTableColumnModification} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected AddTableColumnModificationItemProvider addTableColumnModificationItemProvider;

	/**
	 * This creates an adapter for a {@link com.hundsun.ares.studio.jres.model.chouse.AddTableColumnModification}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createAddTableColumnModificationAdapter() {
		if (addTableColumnModificationItemProvider == null) {
			addTableColumnModificationItemProvider = new AddTableColumnModificationItemProvider(this);
		}

		return addTableColumnModificationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.hundsun.ares.studio.jres.model.chouse.RemoveTableColumnModification} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected RemoveTableColumnModificationItemProvider removeTableColumnModificationItemProvider;

	/**
	 * This creates an adapter for a {@link com.hundsun.ares.studio.jres.model.chouse.RemoveTableColumnModification}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createRemoveTableColumnModificationAdapter() {
		if (removeTableColumnModificationItemProvider == null) {
			removeTableColumnModificationItemProvider = new RemoveTableColumnModificationItemProvider(this);
		}

		return removeTableColumnModificationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.hundsun.ares.studio.jres.model.chouse.RemovedTableColumn} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected RemovedTableColumnItemProvider removedTableColumnItemProvider;

	/**
	 * This creates an adapter for a {@link com.hundsun.ares.studio.jres.model.chouse.RemovedTableColumn}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createRemovedTableColumnAdapter() {
		if (removedTableColumnItemProvider == null) {
			removedTableColumnItemProvider = new RemovedTableColumnItemProvider(this);
		}

		return removedTableColumnItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.hundsun.ares.studio.jres.model.chouse.RenameTableColumnModification} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected RenameTableColumnModificationItemProvider renameTableColumnModificationItemProvider;

	/**
	 * This creates an adapter for a {@link com.hundsun.ares.studio.jres.model.chouse.RenameTableColumnModification}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createRenameTableColumnModificationAdapter() {
		if (renameTableColumnModificationItemProvider == null) {
			renameTableColumnModificationItemProvider = new RenameTableColumnModificationItemProvider(this);
		}

		return renameTableColumnModificationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.hundsun.ares.studio.jres.model.chouse.RTCMDetail} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected RTCMDetailItemProvider rtcmDetailItemProvider;

	/**
	 * This creates an adapter for a {@link com.hundsun.ares.studio.jres.model.chouse.RTCMDetail}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createRTCMDetailAdapter() {
		if (rtcmDetailItemProvider == null) {
			rtcmDetailItemProvider = new RTCMDetailItemProvider(this);
		}

		return rtcmDetailItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.hundsun.ares.studio.jres.model.chouse.ColumnChangeDetail} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ColumnChangeDetailItemProvider columnChangeDetailItemProvider;

	/**
	 * This creates an adapter for a {@link com.hundsun.ares.studio.jres.model.chouse.ColumnChangeDetail}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createColumnChangeDetailAdapter() {
		if (columnChangeDetailItemProvider == null) {
			columnChangeDetailItemProvider = new ColumnChangeDetailItemProvider(this);
		}

		return columnChangeDetailItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.hundsun.ares.studio.jres.model.chouse.ChangeTableColumnTypeModification} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ChangeTableColumnTypeModificationItemProvider changeTableColumnTypeModificationItemProvider;

	/**
	 * This creates an adapter for a {@link com.hundsun.ares.studio.jres.model.chouse.ChangeTableColumnTypeModification}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createChangeTableColumnTypeModificationAdapter() {
		if (changeTableColumnTypeModificationItemProvider == null) {
			changeTableColumnTypeModificationItemProvider = new ChangeTableColumnTypeModificationItemProvider(this);
		}

		return changeTableColumnTypeModificationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.hundsun.ares.studio.jres.model.chouse.CTCTMDetail} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CTCTMDetailItemProvider ctctmDetailItemProvider;

	/**
	 * This creates an adapter for a {@link com.hundsun.ares.studio.jres.model.chouse.CTCTMDetail}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCTCTMDetailAdapter() {
		if (ctctmDetailItemProvider == null) {
			ctctmDetailItemProvider = new CTCTMDetailItemProvider(this);
		}

		return ctctmDetailItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.hundsun.ares.studio.jres.model.chouse.AddIndexModification} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected AddIndexModificationItemProvider addIndexModificationItemProvider;

	/**
	 * This creates an adapter for a {@link com.hundsun.ares.studio.jres.model.chouse.AddIndexModification}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createAddIndexModificationAdapter() {
		if (addIndexModificationItemProvider == null) {
			addIndexModificationItemProvider = new AddIndexModificationItemProvider(this);
		}

		return addIndexModificationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.hundsun.ares.studio.jres.model.chouse.RemoveIndexModification} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected RemoveIndexModificationItemProvider removeIndexModificationItemProvider;

	/**
	 * This creates an adapter for a {@link com.hundsun.ares.studio.jres.model.chouse.RemoveIndexModification}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createRemoveIndexModificationAdapter() {
		if (removeIndexModificationItemProvider == null) {
			removeIndexModificationItemProvider = new RemoveIndexModificationItemProvider(this);
		}

		return removeIndexModificationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.hundsun.ares.studio.jres.model.chouse.RemovedIndex} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected RemovedIndexItemProvider removedIndexItemProvider;

	/**
	 * This creates an adapter for a {@link com.hundsun.ares.studio.jres.model.chouse.RemovedIndex}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createRemovedIndexAdapter() {
		if (removedIndexItemProvider == null) {
			removedIndexItemProvider = new RemovedIndexItemProvider(this);
		}

		return removedIndexItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.hundsun.ares.studio.jres.model.chouse.ChangeTableColumnPrimaryKeyModifycation} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ChangeTableColumnPrimaryKeyModifycationItemProvider changeTableColumnPrimaryKeyModifycationItemProvider;

	/**
	 * This creates an adapter for a {@link com.hundsun.ares.studio.jres.model.chouse.ChangeTableColumnPrimaryKeyModifycation}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createChangeTableColumnPrimaryKeyModifycationAdapter() {
		if (changeTableColumnPrimaryKeyModifycationItemProvider == null) {
			changeTableColumnPrimaryKeyModifycationItemProvider = new ChangeTableColumnPrimaryKeyModifycationItemProvider(this);
		}

		return changeTableColumnPrimaryKeyModifycationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.hundsun.ares.studio.jres.model.chouse.CTCPMDetail} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CTCPMDetailItemProvider ctcpmDetailItemProvider;

	/**
	 * This creates an adapter for a {@link com.hundsun.ares.studio.jres.model.chouse.CTCPMDetail}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCTCPMDetailAdapter() {
		if (ctcpmDetailItemProvider == null) {
			ctcpmDetailItemProvider = new CTCPMDetailItemProvider(this);
		}

		return ctcpmDetailItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.hundsun.ares.studio.jres.model.chouse.ChangeTableColumnUniqueModifycation} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ChangeTableColumnUniqueModifycationItemProvider changeTableColumnUniqueModifycationItemProvider;

	/**
	 * This creates an adapter for a {@link com.hundsun.ares.studio.jres.model.chouse.ChangeTableColumnUniqueModifycation}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createChangeTableColumnUniqueModifycationAdapter() {
		if (changeTableColumnUniqueModifycationItemProvider == null) {
			changeTableColumnUniqueModifycationItemProvider = new ChangeTableColumnUniqueModifycationItemProvider(this);
		}

		return changeTableColumnUniqueModifycationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.hundsun.ares.studio.jres.model.chouse.CTCUMDetail} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CTCUMDetailItemProvider ctcumDetailItemProvider;

	/**
	 * This creates an adapter for a {@link com.hundsun.ares.studio.jres.model.chouse.CTCUMDetail}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCTCUMDetailAdapter() {
		if (ctcumDetailItemProvider == null) {
			ctcumDetailItemProvider = new CTCUMDetailItemProvider(this);
		}

		return ctcumDetailItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.hundsun.ares.studio.jres.model.chouse.ModifyDetail} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ModifyDetailItemProvider modifyDetailItemProvider;

	/**
	 * This creates an adapter for a {@link com.hundsun.ares.studio.jres.model.chouse.ModifyDetail}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createModifyDetailAdapter() {
		if (modifyDetailItemProvider == null) {
			modifyDetailItemProvider = new ModifyDetailItemProvider(this);
		}

		return modifyDetailItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.hundsun.ares.studio.jres.model.chouse.ChangeTableColumnNullableModifycation} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ChangeTableColumnNullableModifycationItemProvider changeTableColumnNullableModifycationItemProvider;

	/**
	 * This creates an adapter for a {@link com.hundsun.ares.studio.jres.model.chouse.ChangeTableColumnNullableModifycation}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createChangeTableColumnNullableModifycationAdapter() {
		if (changeTableColumnNullableModifycationItemProvider == null) {
			changeTableColumnNullableModifycationItemProvider = new ChangeTableColumnNullableModifycationItemProvider(this);
		}

		return changeTableColumnNullableModifycationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.hundsun.ares.studio.jres.model.chouse.CTCNMDetail} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CTCNMDetailItemProvider ctcnmDetailItemProvider;

	/**
	 * This creates an adapter for a {@link com.hundsun.ares.studio.jres.model.chouse.CTCNMDetail}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCTCNMDetailAdapter() {
		if (ctcnmDetailItemProvider == null) {
			ctcnmDetailItemProvider = new CTCNMDetailItemProvider(this);
		}

		return ctcnmDetailItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.hundsun.ares.studio.jres.model.chouse.AddTableColumnPKModification} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected AddTableColumnPKModificationItemProvider addTableColumnPKModificationItemProvider;

	/**
	 * This creates an adapter for a {@link com.hundsun.ares.studio.jres.model.chouse.AddTableColumnPKModification}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createAddTableColumnPKModificationAdapter() {
		if (addTableColumnPKModificationItemProvider == null) {
			addTableColumnPKModificationItemProvider = new AddTableColumnPKModificationItemProvider(this);
		}

		return addTableColumnPKModificationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.hundsun.ares.studio.jres.model.chouse.RemoveTableColumnPKModification} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected RemoveTableColumnPKModificationItemProvider removeTableColumnPKModificationItemProvider;

	/**
	 * This creates an adapter for a {@link com.hundsun.ares.studio.jres.model.chouse.RemoveTableColumnPKModification}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createRemoveTableColumnPKModificationAdapter() {
		if (removeTableColumnPKModificationItemProvider == null) {
			removeTableColumnPKModificationItemProvider = new RemoveTableColumnPKModificationItemProvider(this);
		}

		return removeTableColumnPKModificationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.hundsun.ares.studio.jres.model.chouse.AddTableColumnUniqueModifycation} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected AddTableColumnUniqueModifycationItemProvider addTableColumnUniqueModifycationItemProvider;

	/**
	 * This creates an adapter for a {@link com.hundsun.ares.studio.jres.model.chouse.AddTableColumnUniqueModifycation}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createAddTableColumnUniqueModifycationAdapter() {
		if (addTableColumnUniqueModifycationItemProvider == null) {
			addTableColumnUniqueModifycationItemProvider = new AddTableColumnUniqueModifycationItemProvider(this);
		}

		return addTableColumnUniqueModifycationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.hundsun.ares.studio.jres.model.chouse.RemoveTableColumnUniqueModifycation} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected RemoveTableColumnUniqueModifycationItemProvider removeTableColumnUniqueModifycationItemProvider;

	/**
	 * This creates an adapter for a {@link com.hundsun.ares.studio.jres.model.chouse.RemoveTableColumnUniqueModifycation}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createRemoveTableColumnUniqueModifycationAdapter() {
		if (removeTableColumnUniqueModifycationItemProvider == null) {
			removeTableColumnUniqueModifycationItemProvider = new RemoveTableColumnUniqueModifycationItemProvider(this);
		}

		return removeTableColumnUniqueModifycationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.hundsun.ares.studio.jres.model.chouse.AddConstraintModification} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected AddConstraintModificationItemProvider addConstraintModificationItemProvider;

	/**
	 * This creates an adapter for a {@link com.hundsun.ares.studio.jres.model.chouse.AddConstraintModification}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createAddConstraintModificationAdapter() {
		if (addConstraintModificationItemProvider == null) {
			addConstraintModificationItemProvider = new AddConstraintModificationItemProvider(this);
		}

		return addConstraintModificationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.hundsun.ares.studio.jres.model.chouse.RemoveConstraintModification} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected RemoveConstraintModificationItemProvider removeConstraintModificationItemProvider;

	/**
	 * This creates an adapter for a {@link com.hundsun.ares.studio.jres.model.chouse.RemoveConstraintModification}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createRemoveConstraintModificationAdapter() {
		if (removeConstraintModificationItemProvider == null) {
			removeConstraintModificationItemProvider = new RemoveConstraintModificationItemProvider(this);
		}

		return removeConstraintModificationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.hundsun.ares.studio.jres.model.chouse.ConstraintModifyDetail} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ConstraintModifyDetailItemProvider constraintModifyDetailItemProvider;

	/**
	 * This creates an adapter for a {@link com.hundsun.ares.studio.jres.model.chouse.ConstraintModifyDetail}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createConstraintModifyDetailAdapter() {
		if (constraintModifyDetailItemProvider == null) {
			constraintModifyDetailItemProvider = new ConstraintModifyDetailItemProvider(this);
		}

		return constraintModifyDetailItemProvider;
	}

	/**
	 * This returns the root adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public ComposeableAdapterFactory getRootAdapterFactory() {
		return parentAdapterFactory == null ? this : parentAdapterFactory.getRootAdapterFactory();
	}

	/**
	 * This sets the composed adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void setParentAdapterFactory(ComposedAdapterFactory parentAdapterFactory) {
		this.parentAdapterFactory = parentAdapterFactory;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public boolean isFactoryForType(Object type) {
		return supportedTypes.contains(type) || super.isFactoryForType(type);
	}

	/**
	 * This implementation substitutes the factory itself as the key for the adapter.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter adapt(Notifier notifier, Object type) {
		return super.adapt(notifier, this);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Object adapt(Object object, Object type) {
		if (isFactoryForType(type)) {
			Object adapter = super.adapt(object, type);
			if (!(type instanceof Class<?>) || (((Class<?>)type).isInstance(adapter))) {
				return adapter;
			}
		}

		return null;
	}

	/**
	 * This adds a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void addListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.addListener(notifyChangedListener);
	}

	/**
	 * This removes a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void removeListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.removeListener(notifyChangedListener);
	}

	/**
	 * This delegates to {@link #changeNotifier} and to {@link #parentAdapterFactory}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void fireNotifyChanged(Notification notification) {
		changeNotifier.fireNotifyChanged(notification);

		if (parentAdapterFactory != null) {
			parentAdapterFactory.fireNotifyChanged(notification);
		}
	}

	/**
	 * This disposes all of the item providers created by this factory. 
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void dispose() {
		if (tableSpacePropertyItemProvider != null) tableSpacePropertyItemProvider.dispose();
		if (tableSpaceRelationPropertyItemProvider != null) tableSpaceRelationPropertyItemProvider.dispose();
		if (tableBasePropertyItemProvider != null) tableBasePropertyItemProvider.dispose();
		if (historyPropertyItemProvider != null) historyPropertyItemProvider.dispose();
		if (revisionHistoryPropertyItemProvider != null) revisionHistoryPropertyItemProvider.dispose();
		if (modificationItemProvider != null) modificationItemProvider.dispose();
		if (stockTablePropertyItemProvider != null) stockTablePropertyItemProvider.dispose();
		if (stockColumnPropertyItemProvider != null) stockColumnPropertyItemProvider.dispose();
		if (stockIndexPropertyItemProvider != null) stockIndexPropertyItemProvider.dispose();
		if (stockTSRelationPropertyItemProvider != null) stockTSRelationPropertyItemProvider.dispose();
		if (stockProjectPropertyItemProvider != null) stockProjectPropertyItemProvider.dispose();
		if (stockDBContextPropertyItemProvider != null) stockDBContextPropertyItemProvider.dispose();
		if (addTableModificationItemProvider != null) addTableModificationItemProvider.dispose();
		if (hisTableColumnItemProvider != null) hisTableColumnItemProvider.dispose();
		if (addTableColumnModificationItemProvider != null) addTableColumnModificationItemProvider.dispose();
		if (removeTableColumnModificationItemProvider != null) removeTableColumnModificationItemProvider.dispose();
		if (removedTableColumnItemProvider != null) removedTableColumnItemProvider.dispose();
		if (renameTableColumnModificationItemProvider != null) renameTableColumnModificationItemProvider.dispose();
		if (rtcmDetailItemProvider != null) rtcmDetailItemProvider.dispose();
		if (columnChangeDetailItemProvider != null) columnChangeDetailItemProvider.dispose();
		if (changeTableColumnTypeModificationItemProvider != null) changeTableColumnTypeModificationItemProvider.dispose();
		if (ctctmDetailItemProvider != null) ctctmDetailItemProvider.dispose();
		if (addIndexModificationItemProvider != null) addIndexModificationItemProvider.dispose();
		if (removeIndexModificationItemProvider != null) removeIndexModificationItemProvider.dispose();
		if (removedIndexItemProvider != null) removedIndexItemProvider.dispose();
		if (changeTableColumnPrimaryKeyModifycationItemProvider != null) changeTableColumnPrimaryKeyModifycationItemProvider.dispose();
		if (ctcpmDetailItemProvider != null) ctcpmDetailItemProvider.dispose();
		if (changeTableColumnUniqueModifycationItemProvider != null) changeTableColumnUniqueModifycationItemProvider.dispose();
		if (ctcumDetailItemProvider != null) ctcumDetailItemProvider.dispose();
		if (modifyDetailItemProvider != null) modifyDetailItemProvider.dispose();
		if (changeTableColumnNullableModifycationItemProvider != null) changeTableColumnNullableModifycationItemProvider.dispose();
		if (ctcnmDetailItemProvider != null) ctcnmDetailItemProvider.dispose();
		if (addTableColumnPKModificationItemProvider != null) addTableColumnPKModificationItemProvider.dispose();
		if (removeTableColumnPKModificationItemProvider != null) removeTableColumnPKModificationItemProvider.dispose();
		if (addTableColumnUniqueModifycationItemProvider != null) addTableColumnUniqueModifycationItemProvider.dispose();
		if (removeTableColumnUniqueModifycationItemProvider != null) removeTableColumnUniqueModifycationItemProvider.dispose();
		if (addConstraintModificationItemProvider != null) addConstraintModificationItemProvider.dispose();
		if (removeConstraintModificationItemProvider != null) removeConstraintModificationItemProvider.dispose();
		if (constraintModifyDetailItemProvider != null) constraintModifyDetailItemProvider.dispose();
	}

}
