/**
 * <p>Copyright: Copyright (c) 2011</p>
 * <p>Company: 恒生电子股份有限公司</p>
 */
package com.hundsun.ares.studio.jres.model.metadata.provider;

import com.hundsun.ares.studio.jres.model.metadata.util.MetadataAdapterFactory;

import java.util.ArrayList;
import java.util.Collection;

import org.eclipse.emf.common.notify.Adapter;
import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.Notifier;

import org.eclipse.emf.edit.provider.ChangeNotifier;
import org.eclipse.emf.edit.provider.ComposeableAdapterFactory;
import org.eclipse.emf.edit.provider.ComposedAdapterFactory;
import org.eclipse.emf.edit.provider.IChangeNotifier;
import org.eclipse.emf.edit.provider.IDisposable;
import org.eclipse.emf.edit.provider.IEditingDomainItemProvider;
import org.eclipse.emf.edit.provider.IItemLabelProvider;
import org.eclipse.emf.edit.provider.IItemPropertySource;
import org.eclipse.emf.edit.provider.INotifyChangedListener;
import org.eclipse.emf.edit.provider.IStructuredItemContentProvider;
import org.eclipse.emf.edit.provider.ITreeItemContentProvider;

/**
 * This is the factory that is used to provide the interfaces needed to support Viewers.
 * The adapters generated by this factory convert EMF adapter notifications into calls to {@link #fireNotifyChanged fireNotifyChanged}.
 * The adapters also support Eclipse property sheets.
 * Note that most of the adapters are shared among multiple instances.
 * <!-- begin-user-doc -->
 * <!-- end-user-doc -->
 * @generated
 */
public class MetadataItemProviderAdapterFactory extends MetadataAdapterFactory implements ComposeableAdapterFactory, IChangeNotifier, IDisposable {
	/**
	 * This keeps track of the root adapter factory that delegates to this adapter factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ComposedAdapterFactory parentAdapterFactory;

	/**
	 * This is used to implement {@link org.eclipse.emf.edit.provider.IChangeNotifier}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IChangeNotifier changeNotifier = new ChangeNotifier();

	/**
	 * This keeps track of all the supported types checked by {@link #isFactoryForType isFactoryForType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Collection<Object> supportedTypes = new ArrayList<Object>();

	/**
	 * This constructs an instance.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public MetadataItemProviderAdapterFactory() {
		supportedTypes.add(IEditingDomainItemProvider.class);
		supportedTypes.add(IStructuredItemContentProvider.class);
		supportedTypes.add(ITreeItemContentProvider.class);
		supportedTypes.add(IItemLabelProvider.class);
		supportedTypes.add(IItemPropertySource.class);
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.hundsun.ares.studio.jres.model.metadata.MDModuleCommonProperty} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected MDModuleCommonPropertyItemProvider mdModuleCommonPropertyItemProvider;

	/**
	 * This creates an adapter for a {@link com.hundsun.ares.studio.jres.model.metadata.MDModuleCommonProperty}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createMDModuleCommonPropertyAdapter() {
		if (mdModuleCommonPropertyItemProvider == null) {
			mdModuleCommonPropertyItemProvider = new MDModuleCommonPropertyItemProvider(this);
		}

		return mdModuleCommonPropertyItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.hundsun.ares.studio.jres.model.metadata.Operation} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected OperationItemProvider operationItemProvider;

	/**
	 * This creates an adapter for a {@link com.hundsun.ares.studio.jres.model.metadata.Operation}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createOperationAdapter() {
		if (operationItemProvider == null) {
			operationItemProvider = new OperationItemProvider(this);
		}

		return operationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.hundsun.ares.studio.jres.model.metadata.NamedElement} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected NamedElementItemProvider namedElementItemProvider;

	/**
	 * This creates an adapter for a {@link com.hundsun.ares.studio.jres.model.metadata.NamedElement}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createNamedElementAdapter() {
		if (namedElementItemProvider == null) {
			namedElementItemProvider = new NamedElementItemProvider(this);
		}

		return namedElementItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.hundsun.ares.studio.jres.model.metadata.MetadataItem} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected MetadataItemItemProvider metadataItemItemProvider;

	/**
	 * This creates an adapter for a {@link com.hundsun.ares.studio.jres.model.metadata.MetadataItem}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createMetadataItemAdapter() {
		if (metadataItemItemProvider == null) {
			metadataItemItemProvider = new MetadataItemItemProvider(this);
		}

		return metadataItemItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.hundsun.ares.studio.jres.model.metadata.MetadataCategory} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected MetadataCategoryItemProvider metadataCategoryItemProvider;

	/**
	 * This creates an adapter for a {@link com.hundsun.ares.studio.jres.model.metadata.MetadataCategory}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createMetadataCategoryAdapter() {
		if (metadataCategoryItemProvider == null) {
			metadataCategoryItemProvider = new MetadataCategoryItemProvider(this);
		}

		return metadataCategoryItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.hundsun.ares.studio.jres.model.metadata.TypeDefaultValueList} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected TypeDefaultValueListItemProvider typeDefaultValueListItemProvider;

	/**
	 * This creates an adapter for a {@link com.hundsun.ares.studio.jres.model.metadata.TypeDefaultValueList}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTypeDefaultValueListAdapter() {
		if (typeDefaultValueListItemProvider == null) {
			typeDefaultValueListItemProvider = new TypeDefaultValueListItemProvider(this);
		}

		return typeDefaultValueListItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.hundsun.ares.studio.jres.model.metadata.TypeDefaultValue} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected TypeDefaultValueItemProvider typeDefaultValueItemProvider;

	/**
	 * This creates an adapter for a {@link com.hundsun.ares.studio.jres.model.metadata.TypeDefaultValue}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTypeDefaultValueAdapter() {
		if (typeDefaultValueItemProvider == null) {
			typeDefaultValueItemProvider = new TypeDefaultValueItemProvider(this);
		}

		return typeDefaultValueItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.hundsun.ares.studio.jres.model.metadata.StandardDataTypeList} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected StandardDataTypeListItemProvider standardDataTypeListItemProvider;

	/**
	 * This creates an adapter for a {@link com.hundsun.ares.studio.jres.model.metadata.StandardDataTypeList}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createStandardDataTypeListAdapter() {
		if (standardDataTypeListItemProvider == null) {
			standardDataTypeListItemProvider = new StandardDataTypeListItemProvider(this);
		}

		return standardDataTypeListItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.hundsun.ares.studio.jres.model.metadata.StandardDataType} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected StandardDataTypeItemProvider standardDataTypeItemProvider;

	/**
	 * This creates an adapter for a {@link com.hundsun.ares.studio.jres.model.metadata.StandardDataType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createStandardDataTypeAdapter() {
		if (standardDataTypeItemProvider == null) {
			standardDataTypeItemProvider = new StandardDataTypeItemProvider(this);
		}

		return standardDataTypeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.hundsun.ares.studio.jres.model.metadata.BusinessDataTypeList} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected BusinessDataTypeListItemProvider businessDataTypeListItemProvider;

	/**
	 * This creates an adapter for a {@link com.hundsun.ares.studio.jres.model.metadata.BusinessDataTypeList}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createBusinessDataTypeListAdapter() {
		if (businessDataTypeListItemProvider == null) {
			businessDataTypeListItemProvider = new BusinessDataTypeListItemProvider(this);
		}

		return businessDataTypeListItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.hundsun.ares.studio.jres.model.metadata.BusinessDataType} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected BusinessDataTypeItemProvider businessDataTypeItemProvider;

	/**
	 * This creates an adapter for a {@link com.hundsun.ares.studio.jres.model.metadata.BusinessDataType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createBusinessDataTypeAdapter() {
		if (businessDataTypeItemProvider == null) {
			businessDataTypeItemProvider = new BusinessDataTypeItemProvider(this);
		}

		return businessDataTypeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.hundsun.ares.studio.jres.model.metadata.StandardFieldList} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected StandardFieldListItemProvider standardFieldListItemProvider;

	/**
	 * This creates an adapter for a {@link com.hundsun.ares.studio.jres.model.metadata.StandardFieldList}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createStandardFieldListAdapter() {
		if (standardFieldListItemProvider == null) {
			standardFieldListItemProvider = new StandardFieldListItemProvider(this);
		}

		return standardFieldListItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.hundsun.ares.studio.jres.model.metadata.StandardField} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected StandardFieldItemProvider standardFieldItemProvider;

	/**
	 * This creates an adapter for a {@link com.hundsun.ares.studio.jres.model.metadata.StandardField}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createStandardFieldAdapter() {
		if (standardFieldItemProvider == null) {
			standardFieldItemProvider = new StandardFieldItemProvider(this);
		}

		return standardFieldItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.hundsun.ares.studio.jres.model.metadata.DictionaryList} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DictionaryListItemProvider dictionaryListItemProvider;

	/**
	 * This creates an adapter for a {@link com.hundsun.ares.studio.jres.model.metadata.DictionaryList}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDictionaryListAdapter() {
		if (dictionaryListItemProvider == null) {
			dictionaryListItemProvider = new DictionaryListItemProvider(this);
		}

		return dictionaryListItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.hundsun.ares.studio.jres.model.metadata.DictionaryType} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DictionaryTypeItemProvider dictionaryTypeItemProvider;

	/**
	 * This creates an adapter for a {@link com.hundsun.ares.studio.jres.model.metadata.DictionaryType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDictionaryTypeAdapter() {
		if (dictionaryTypeItemProvider == null) {
			dictionaryTypeItemProvider = new DictionaryTypeItemProvider(this);
		}

		return dictionaryTypeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.hundsun.ares.studio.jres.model.metadata.DictionaryItem} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DictionaryItemItemProvider dictionaryItemItemProvider;

	/**
	 * This creates an adapter for a {@link com.hundsun.ares.studio.jres.model.metadata.DictionaryItem}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDictionaryItemAdapter() {
		if (dictionaryItemItemProvider == null) {
			dictionaryItemItemProvider = new DictionaryItemItemProvider(this);
		}

		return dictionaryItemItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.hundsun.ares.studio.jres.model.metadata.ConstantList} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ConstantListItemProvider constantListItemProvider;

	/**
	 * This creates an adapter for a {@link com.hundsun.ares.studio.jres.model.metadata.ConstantList}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createConstantListAdapter() {
		if (constantListItemProvider == null) {
			constantListItemProvider = new ConstantListItemProvider(this);
		}

		return constantListItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.hundsun.ares.studio.jres.model.metadata.ConstantItem} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ConstantItemItemProvider constantItemItemProvider;

	/**
	 * This creates an adapter for a {@link com.hundsun.ares.studio.jres.model.metadata.ConstantItem}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createConstantItemAdapter() {
		if (constantItemItemProvider == null) {
			constantItemItemProvider = new ConstantItemItemProvider(this);
		}

		return constantItemItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.hundsun.ares.studio.jres.model.metadata.ErrorNoList} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ErrorNoListItemProvider errorNoListItemProvider;

	/**
	 * This creates an adapter for a {@link com.hundsun.ares.studio.jres.model.metadata.ErrorNoList}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createErrorNoListAdapter() {
		if (errorNoListItemProvider == null) {
			errorNoListItemProvider = new ErrorNoListItemProvider(this);
		}

		return errorNoListItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.hundsun.ares.studio.jres.model.metadata.ErrorNoItem} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ErrorNoItemItemProvider errorNoItemItemProvider;

	/**
	 * This creates an adapter for a {@link com.hundsun.ares.studio.jres.model.metadata.ErrorNoItem}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createErrorNoItemAdapter() {
		if (errorNoItemItemProvider == null) {
			errorNoItemItemProvider = new ErrorNoItemItemProvider(this);
		}

		return errorNoItemItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.hundsun.ares.studio.jres.model.metadata.GeneralDataConfigList} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected GeneralDataConfigListItemProvider generalDataConfigListItemProvider;

	/**
	 * This creates an adapter for a {@link com.hundsun.ares.studio.jres.model.metadata.GeneralDataConfigList}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createGeneralDataConfigListAdapter() {
		if (generalDataConfigListItemProvider == null) {
			generalDataConfigListItemProvider = new GeneralDataConfigListItemProvider(this);
		}

		return generalDataConfigListItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.hundsun.ares.studio.jres.model.metadata.GeneralDataConfigItem} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected GeneralDataConfigItemItemProvider generalDataConfigItemItemProvider;

	/**
	 * This creates an adapter for a {@link com.hundsun.ares.studio.jres.model.metadata.GeneralDataConfigItem}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createGeneralDataConfigItemAdapter() {
		if (generalDataConfigItemItemProvider == null) {
			generalDataConfigItemItemProvider = new GeneralDataConfigItemItemProvider(this);
		}

		return generalDataConfigItemItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.hundsun.ares.studio.jres.model.metadata.MenuItem} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected MenuItemItemProvider menuItemItemProvider;

	/**
	 * This creates an adapter for a {@link com.hundsun.ares.studio.jres.model.metadata.MenuItem}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createMenuItemAdapter() {
		if (menuItemItemProvider == null) {
			menuItemItemProvider = new MenuItemItemProvider(this);
		}

		return menuItemItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.hundsun.ares.studio.jres.model.metadata.FunctionProxy} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected FunctionProxyItemProvider functionProxyItemProvider;

	/**
	 * This creates an adapter for a {@link com.hundsun.ares.studio.jres.model.metadata.FunctionProxy}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createFunctionProxyAdapter() {
		if (functionProxyItemProvider == null) {
			functionProxyItemProvider = new FunctionProxyItemProvider(this);
		}

		return functionProxyItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.hundsun.ares.studio.jres.model.metadata.Function} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected FunctionItemProvider functionItemProvider;

	/**
	 * This creates an adapter for a {@link com.hundsun.ares.studio.jres.model.metadata.Function}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createFunctionAdapter() {
		if (functionItemProvider == null) {
			functionItemProvider = new FunctionItemProvider(this);
		}

		return functionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.hundsun.ares.studio.jres.model.metadata.MenuList} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected MenuListItemProvider menuListItemProvider;

	/**
	 * This creates an adapter for a {@link com.hundsun.ares.studio.jres.model.metadata.MenuList}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createMenuListAdapter() {
		if (menuListItemProvider == null) {
			menuListItemProvider = new MenuListItemProvider(this);
		}

		return menuListItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.hundsun.ares.studio.jres.model.metadata.IDRangeItem} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IDRangeItemItemProvider idRangeItemItemProvider;

	/**
	 * This creates an adapter for a {@link com.hundsun.ares.studio.jres.model.metadata.IDRangeItem}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createIDRangeItemAdapter() {
		if (idRangeItemItemProvider == null) {
			idRangeItemItemProvider = new IDRangeItemItemProvider(this);
		}

		return idRangeItemItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.hundsun.ares.studio.jres.model.metadata.IDRange} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IDRangeItemProvider idRangeItemProvider;

	/**
	 * This creates an adapter for a {@link com.hundsun.ares.studio.jres.model.metadata.IDRange}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createIDRangeAdapter() {
		if (idRangeItemProvider == null) {
			idRangeItemProvider = new IDRangeItemProvider(this);
		}

		return idRangeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.hundsun.ares.studio.jres.model.metadata.BizPropertyConfigList} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected BizPropertyConfigListItemProvider bizPropertyConfigListItemProvider;

	/**
	 * This creates an adapter for a {@link com.hundsun.ares.studio.jres.model.metadata.BizPropertyConfigList}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createBizPropertyConfigListAdapter() {
		if (bizPropertyConfigListItemProvider == null) {
			bizPropertyConfigListItemProvider = new BizPropertyConfigListItemProvider(this);
		}

		return bizPropertyConfigListItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.hundsun.ares.studio.jres.model.metadata.BizPropertyConfig} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected BizPropertyConfigItemProvider bizPropertyConfigItemProvider;

	/**
	 * This creates an adapter for a {@link com.hundsun.ares.studio.jres.model.metadata.BizPropertyConfig}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createBizPropertyConfigAdapter() {
		if (bizPropertyConfigItemProvider == null) {
			bizPropertyConfigItemProvider = new BizPropertyConfigItemProvider(this);
		}

		return bizPropertyConfigItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.hundsun.ares.studio.jres.model.metadata.IDRangeList} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IDRangeListItemProvider idRangeListItemProvider;

	/**
	 * This creates an adapter for a {@link com.hundsun.ares.studio.jres.model.metadata.IDRangeList}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createIDRangeListAdapter() {
		if (idRangeListItemProvider == null) {
			idRangeListItemProvider = new IDRangeListItemProvider(this);
		}

		return idRangeListItemProvider;
	}

	/**
	 * This returns the root adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public ComposeableAdapterFactory getRootAdapterFactory() {
		return parentAdapterFactory == null ? this : parentAdapterFactory.getRootAdapterFactory();
	}

	/**
	 * This sets the composed adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void setParentAdapterFactory(ComposedAdapterFactory parentAdapterFactory) {
		this.parentAdapterFactory = parentAdapterFactory;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public boolean isFactoryForType(Object type) {
		return supportedTypes.contains(type) || super.isFactoryForType(type);
	}

	/**
	 * This implementation substitutes the factory itself as the key for the adapter.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter adapt(Notifier notifier, Object type) {
		return super.adapt(notifier, this);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Object adapt(Object object, Object type) {
		if (isFactoryForType(type)) {
			Object adapter = super.adapt(object, type);
			if (!(type instanceof Class<?>) || (((Class<?>)type).isInstance(adapter))) {
				return adapter;
			}
		}

		return null;
	}

	/**
	 * This adds a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void addListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.addListener(notifyChangedListener);
	}

	/**
	 * This removes a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void removeListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.removeListener(notifyChangedListener);
	}

	/**
	 * This delegates to {@link #changeNotifier} and to {@link #parentAdapterFactory}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void fireNotifyChanged(Notification notification) {
		changeNotifier.fireNotifyChanged(notification);

		if (parentAdapterFactory != null) {
			parentAdapterFactory.fireNotifyChanged(notification);
		}
	}

	/**
	 * This disposes all of the item providers created by this factory. 
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void dispose() {
		if (mdModuleCommonPropertyItemProvider != null) mdModuleCommonPropertyItemProvider.dispose();
		if (operationItemProvider != null) operationItemProvider.dispose();
		if (namedElementItemProvider != null) namedElementItemProvider.dispose();
		if (metadataItemItemProvider != null) metadataItemItemProvider.dispose();
		if (metadataCategoryItemProvider != null) metadataCategoryItemProvider.dispose();
		if (typeDefaultValueListItemProvider != null) typeDefaultValueListItemProvider.dispose();
		if (typeDefaultValueItemProvider != null) typeDefaultValueItemProvider.dispose();
		if (standardDataTypeListItemProvider != null) standardDataTypeListItemProvider.dispose();
		if (standardDataTypeItemProvider != null) standardDataTypeItemProvider.dispose();
		if (businessDataTypeListItemProvider != null) businessDataTypeListItemProvider.dispose();
		if (businessDataTypeItemProvider != null) businessDataTypeItemProvider.dispose();
		if (standardFieldListItemProvider != null) standardFieldListItemProvider.dispose();
		if (standardFieldItemProvider != null) standardFieldItemProvider.dispose();
		if (dictionaryListItemProvider != null) dictionaryListItemProvider.dispose();
		if (dictionaryTypeItemProvider != null) dictionaryTypeItemProvider.dispose();
		if (dictionaryItemItemProvider != null) dictionaryItemItemProvider.dispose();
		if (constantListItemProvider != null) constantListItemProvider.dispose();
		if (constantItemItemProvider != null) constantItemItemProvider.dispose();
		if (errorNoListItemProvider != null) errorNoListItemProvider.dispose();
		if (errorNoItemItemProvider != null) errorNoItemItemProvider.dispose();
		if (generalDataConfigListItemProvider != null) generalDataConfigListItemProvider.dispose();
		if (generalDataConfigItemItemProvider != null) generalDataConfigItemItemProvider.dispose();
		if (menuItemItemProvider != null) menuItemItemProvider.dispose();
		if (functionProxyItemProvider != null) functionProxyItemProvider.dispose();
		if (functionItemProvider != null) functionItemProvider.dispose();
		if (menuListItemProvider != null) menuListItemProvider.dispose();
		if (idRangeItemItemProvider != null) idRangeItemItemProvider.dispose();
		if (idRangeListItemProvider != null) idRangeListItemProvider.dispose();
		if (idRangeItemProvider != null) idRangeItemProvider.dispose();
		if (bizPropertyConfigListItemProvider != null) bizPropertyConfigListItemProvider.dispose();
		if (bizPropertyConfigItemProvider != null) bizPropertyConfigItemProvider.dispose();
	}

}
