<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="logic"
    nsURI="http://www.hundsun.com/ares/studio/cres/logic/1.0.0" nsPrefix="logic">
  <eClassifiers xsi:type="ecore:EClass" name="LogicFunction" eSuperTypes="../../com.hundsun.ares.studio.atom.core/model/atom.ecore#//AtomFunction">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="objectId"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isTransFunc" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LogicService" eSuperTypes="../../com.hundsun.ares.studio.atom.core/model/atom.ecore#//AtomFunction">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="objectId"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isCheckAccess" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="timeOut" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral=""/>
  </eClassifiers>
</ecore:EPackage>
