<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="flow"
    nsURI="http://com.hundsun.ares.studio.flow" nsPrefix="flow">
  <eClassifiers xsi:type="ecore:EClass" name="IViewProvider" abstract="true">
    <eOperations name="getView" eType="#//IDataView">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="return new IDataViewImpl();"/>
      </eAnnotations>
    </eOperations>
    <eOperations name="getData" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="return null;"/>
      </eAnnotations>
    </eOperations>
    <eOperations name="getFigureNode" eType="#//FigureNode">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="return null;"/>
      </eAnnotations>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FigureNode">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral=""/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="colorView" eType="#//ColorView"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="bounds" eType="#//Rectangle"
        defaultValueLiteral="0,0,0,0"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Begin" abstract="true" eSuperTypes="#//IViewProvider">
    <eStructuralFeatures xsi:type="ecore:EReference" name="figureNode" eType="#//FigureNode"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="End" abstract="true" eSuperTypes="#//IViewProvider">
    <eStructuralFeatures xsi:type="ecore:EReference" name="figureNode" eType="#//FigureNode"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FlowNode" abstract="true" eSuperTypes="#//IViewProvider">
    <eStructuralFeatures xsi:type="ecore:EReference" name="figureNode" eType="#//FigureNode"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IDataView">
    <eOperations name="getToolTip">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="return new BasicEList&lt;String>();"/>
      </eAnnotations>
      <eGenericType eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EEList">
        <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      </eGenericType>
    </eOperations>
    <eOperations name="getId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="return StringUtils.EMPTY;"/>
      </eAnnotations>
    </eOperations>
    <eOperations name="getName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="return StringUtils.EMPTY;"/>
      </eAnnotations>
    </eOperations>
    <eOperations name="getDefaultAnchor" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="return StringUtils.EMPTY;"/>
      </eAnnotations>
    </eOperations>
    <eOperations name="getAnchors">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="return new BasicEList&lt;String>();"/>
      </eAnnotations>
      <eGenericType eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EEList">
        <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      </eGenericType>
    </eOperations>
    <eOperations name="getDescrition" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="return StringUtils.EMPTY;"/>
      </eAnnotations>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Connection">
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" eType="#//IViewProvider"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" eType="#//IViewProvider"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="colorView" eType="#//ColorView"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral=""/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="bendpoints" upperBound="-1"
        eType="#//Bendpoint" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ColorView">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="frontground" eType="#//RGB"
        defaultValueLiteral="0,0,0"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="background" eType="#//RGB"
        defaultValueLiteral="255,255,255"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Bendpoint">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="firstRelative" eType="#//Dimension"
        defaultValueLiteral="0,0"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="secondRelative" eType="#//Dimension"
        defaultValueLiteral="0,0"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FlowModel" abstract="true">
    <eTypeParameters name="T">
      <eBounds eClassifier="#//FlowNode"/>
    </eTypeParameters>
    <eTypeParameters name="K">
      <eBounds eClassifier="#//Begin"/>
    </eTypeParameters>
    <eTypeParameters name="V">
      <eBounds eClassifier="#//End"/>
    </eTypeParameters>
    <eStructuralFeatures xsi:type="ecore:EReference" name="begin" containment="true">
      <eGenericType eTypeParameter="#//FlowModel/K"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ends" upperBound="-1" containment="true">
      <eGenericType eTypeParameter="#//FlowModel/V"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="nodes" upperBound="-1"
        containment="true">
      <eGenericType eTypeParameter="#//FlowModel/T"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="connections" upperBound="-1"
        eType="#//Connection" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="RGB" instanceClassName="org.eclipse.swt.graphics.RGB"/>
  <eClassifiers xsi:type="ecore:EDataType" name="Point" instanceClassName="org.eclipse.swt.graphics.Point"/>
  <eClassifiers xsi:type="ecore:EDataType" name="Rectangle" instanceClassName="org.eclipse.draw2d.geometry.Rectangle"/>
  <eClassifiers xsi:type="ecore:EDataType" name="Dimension" instanceClassName="org.eclipse.draw2d.geometry.Dimension"/>
</ecore:EPackage>
