<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="chouse"
    nsURI="http://www.hundsun.com/ares/studio/jres/database/chouse/1.0.0" nsPrefix="chouse">
  <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
    <details key="documentation" value="删除的时候信息保存复用ConstraintModifyDetail，但是此时只有name属性有用。"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="TableSpaceProperty">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="reduTable chearTable"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="reduTable" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="chearTable" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="chearTableIndex" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TableSpaceRelationProperty">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="hisSpace hisIndexSpace fileSpace fileIndexSpace"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="hisSpace" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="hisIndexSpace" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fileSpace" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fileIndexSpace" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TableBaseProperty">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="clear redu history historySpace historyIndexSpace objectID splitField splitNum startData userSplit fileSpace fileIndexSpace"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="chear" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="redu" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="history" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="historySpace" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="historyIndexSpace" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="objectID" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="splitField" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="splitNum" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="startData" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="userSplit" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isRedu" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isClear" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fileSpace" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fileIndexSpace" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="clearIndexSpace" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="HistoryProperty">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="internalVersion" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral=""/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RevisionHistoryProperty" eSuperTypes="#//HistoryProperty ../../com.hundsun.ares.studio.core/model/ares.ecore#//IReferenceProvider">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="action"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="action" eType="#//Modification"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="actionType" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="actionDescription" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        volatile="true" transient="true" derived="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Modification" eSuperTypes="../../com.hundsun.ares.studio.core/model/ares.ecore#//ExtensibleModel ../../com.hundsun.ares.studio.core/model/ares.ecore#//IReferenceProvider"/>
  <eClassifiers xsi:type="ecore:EClass" name="StockTableProperty">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="hisSpace hisIndexSpace"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="history" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StockColumnProperty">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="flag"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="flag" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral=""/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StockIndexProperty">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="flag"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="flag" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral=""/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StockTSRelationProperty">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="hisSpace hisIndexSpace"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="hisSpace" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral=""/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="hisIndexSpace" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral=""/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StockProjectProperty">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="baseVersion" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StockDBContextProperty">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="startVersion" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral=""/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="endVersion" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral=""/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AddTableModification" eSuperTypes="#//Modification">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="newSelfTable" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="newHistoryTable" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="columns" upperBound="-1"
        eType="ecore:EClass ../../com.hundsun.ares.studio.jres.database.core/model/database.ecore#//TableColumn"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="indexes" upperBound="-1"
        eType="ecore:EClass ../../com.hundsun.ares.studio.jres.database.core/model/database.ecore#//TableIndex"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="keys" upperBound="-1" eType="ecore:EClass ../../com.hundsun.ares.studio.jres.database.core/model/database.ecore#//TableKey"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="HisTableColumn" eSuperTypes="../../com.hundsun.ares.studio.jres.database.core/model/database.ecore#//TableColumn"/>
  <eClassifiers xsi:type="ecore:EClass" name="AddTableColumnModification" eSuperTypes="#//Modification">
    <eStructuralFeatures xsi:type="ecore:EReference" name="columns" upperBound="-1"
        eType="#//HisTableColumn" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RemoveTableColumnModification" eSuperTypes="#//Modification">
    <eStructuralFeatures xsi:type="ecore:EReference" name="columns" upperBound="-1"
        eType="#//RemovedTableColumn" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RemovedTableColumn" eSuperTypes="../../com.hundsun.ares.studio.jres.database.core/model/database.ecore#//TableColumn"/>
  <eClassifiers xsi:type="ecore:EClass" name="RenameTableColumnModification" eSuperTypes="#//Modification">
    <eStructuralFeatures xsi:type="ecore:EReference" name="details" upperBound="-1"
        eType="#//RTCMDetail" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RTCMDetail" eSuperTypes="#//ColumnChangeDetail">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="newName"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="newName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral=""/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="oldName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="" derived="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="@deprecated&#xD;&#xA;为兼容老系统保留这个属性； 推荐使用getSnapshot().getName()代替"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mark" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="@deprecated"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ColumnChangeDetail">
    <eStructuralFeatures xsi:type="ecore:EReference" name="snapshot" eType="ecore:EClass ../../com.hundsun.ares.studio.jres.database.core/model/database.ecore#//TableColumn"
        containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="基于列的修改Details描述类，每次修改都把列的当前状态作为一个快照保存"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ChangeTableColumnTypeModification" eSuperTypes="#//Modification">
    <eStructuralFeatures xsi:type="ecore:EReference" name="details" upperBound="-1"
        eType="#//CTCTMDetail" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CTCTMDetail" eSuperTypes="#//ColumnChangeDetail">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="@deprecated&#xD;&#xA;为兼容老系统保留这个属性； 推荐使用getSnapshot().getName()代替"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="newType" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral=""/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mark" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="@deprecated"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AddIndexModification" eSuperTypes="#//Modification">
    <eStructuralFeatures xsi:type="ecore:EReference" name="indexs" upperBound="-1"
        eType="ecore:EClass ../../com.hundsun.ares.studio.jres.database.core/model/database.ecore#//TableIndex"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RemoveIndexModification" eSuperTypes="#//Modification">
    <eStructuralFeatures xsi:type="ecore:EReference" name="indexs" upperBound="-1"
        eType="#//RemovedIndex" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AddIndexFieldModification" eSuperTypes="#//Modification">
    <eStructuralFeatures xsi:type="ecore:EReference" name="indexs" upperBound="-1"
        eType="#//AddIndexField" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RemoveIndexFieldModification" eSuperTypes="#//Modification">
    <eStructuralFeatures xsi:type="ecore:EReference" name="indexs" upperBound="-1"
        eType="#//RemoveIndexField" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AddIndexField">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="indexFields" upperBound="-1"
        eType="ecore:EClass ../../com.hundsun.ares.studio.jres.database.core/model/database.ecore#//TableIndexColumn"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mark" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RemoveIndexField">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mark" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="indexFields" upperBound="-1"
        eType="ecore:EClass ../../com.hundsun.ares.studio.jres.database.core/model/database.ecore#//TableIndexColumn"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RemovedIndex">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mark" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ChangeTableColumnPrimaryKeyModifycation"
      eSuperTypes="#//Modification">
    <eStructuralFeatures xsi:type="ecore:EReference" name="details" upperBound="-1"
        eType="#//CTCPMDetail" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CTCPMDetail" eSuperTypes="#//ModifyDetail">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="primarkKey" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ChangeTableColumnUniqueModifycation"
      eSuperTypes="#//Modification">
    <eStructuralFeatures xsi:type="ecore:EReference" name="details" upperBound="-1"
        eType="#//CTCUMDetail" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CTCUMDetail" eSuperTypes="#//ModifyDetail">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="unique" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ModifyDetail" eSuperTypes="#//ColumnChangeDetail">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="@deprecated&#xD;&#xA;为兼容老系统保留这个属性； 推荐使用getSnapshot().getName()代替"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mark" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ChangeTableColumnNullableModifycation"
      eSuperTypes="#//Modification">
    <eStructuralFeatures xsi:type="ecore:EReference" name="details" upperBound="-1"
        eType="#//CTCNMDetail" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CTCNMDetail" eSuperTypes="#//ModifyDetail">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nullable" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AddTableColumnPKModification" eSuperTypes="#//Modification">
    <eStructuralFeatures xsi:type="ecore:EReference" name="details" upperBound="-1"
        eType="#//ModifyDetail" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RemoveTableColumnPKModification" eSuperTypes="#//Modification">
    <eStructuralFeatures xsi:type="ecore:EReference" name="details" upperBound="-1"
        eType="#//ModifyDetail" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AddTableColumnUniqueModifycation" eSuperTypes="#//Modification">
    <eStructuralFeatures xsi:type="ecore:EReference" name="details" upperBound="-1"
        eType="#//ModifyDetail" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RemoveTableColumnUniqueModifycation"
      eSuperTypes="#//Modification">
    <eStructuralFeatures xsi:type="ecore:EReference" name="details" upperBound="-1"
        eType="#//ModifyDetail" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AddConstraintModification" eSuperTypes="#//Modification">
    <eStructuralFeatures xsi:type="ecore:EReference" name="details" upperBound="-1"
        eType="#//ConstraintModifyDetail" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RemoveConstraintModification" eSuperTypes="#//Modification">
    <eStructuralFeatures xsi:type="ecore:EReference" name="details" upperBound="-1"
        eType="#//ConstraintModifyDetail" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ConstraintModifyDetail">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mark" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="标志位"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="约束的名字"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="columns" upperBound="-1"
        eType="ecore:EClass ../../com.hundsun.ares.studio.jres.database.core/model/database.ecore#//TableColumn"
        containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="添加约束的时候指定的列的快照、副本"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="ecore:EEnum ../../com.hundsun.ares.studio.jres.database.core/model/database.ecore#//key_type">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="类型，比如主键，外键，唯一"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="foreignKey" upperBound="-1"
        eType="ecore:EClass ../../com.hundsun.ares.studio.jres.database.core/model/database.ecore#//ForeignKey"
        containment="true"/>
  </eClassifiers>
</ecore:EPackage>
